### ISSUE TITLE
Hide seems to crash the app

### ISSUE THREAD

**Issue by sitefinitysteve** [alexziskind1/nativescript-effects#1]
So this works fine (getElementsByClassName is nathanaels helper, I can assure you it returns something as this works)

``` JS
    var icon = stack.getElementsByClassName("selection-icon")[0];
    icon.fadeOut(1).then(function(){
        if(item.IsSelected){
            icon.text = "\uf00c"

        }else{
            icon.text = "\uf1db"
        }

        icon.fadeIn(50);
    });
```

...but if I change it to 

``` JS
    var icon = stack.getElementsByClassName("selection-icon")[0];
    icon.hide().then(function(){
        if(item.IsSelected){
            icon.text = "\uf00c"

        }else{
            icon.text = "\uf1db"
        }

        icon.fadeIn(50);
    });
```

App crashes

I think (from debugging) "icon.hide()" isnt returning a promise.

**Comment by sitefinitysteve** [comment]
Thx for this plugin though btw :) :+1:

**Comment by alexziskind1** [comment]
Steve,

Thanks for the heads up. This is fixed now.

On Wed, Feb 17, 2016 at 2:18 PM, Steve McNiven-Scott <
notifications@github.com> wrote:

> So this works fine (getElementsByClassName is nathanaels helper, I can
> assure you it returns something as this works)
> 
> ```
> var icon = stack.getElementsByClassName("selection-icon")[0];
> icon.fadeOut(1).then(function(){
>     if(item.IsSelected){
>         icon.text = "\uf00c"
> 
>     }else{
>         icon.text = "\uf1db"
>     }
> 
>     icon.fadeIn(50);
> });
> ```
> 
> ...but if I change it to
> 
> ```
> var icon = stack.getElementsByClassName("selection-icon")[0];
> icon.hide().then(function(){
>     if(item.IsSelected){
>         icon.text = "\uf00c"
> 
>     }else{
>         icon.text = "\uf1db"
>     }
> 
>     icon.fadeIn(50);
> });
> ```
> 
> App crashes
> 
> I think (from debugging) "icon.hide()" isnt returning a promise.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/alexziskind1/nativescript-effects/issues/1.

## 

_Alexander Ziskind_
_(Technical Director)_
_(202) 656-6884_
