### ISSUE TITLE
Support for nativescript 7

### ISSUE THREAD

**Issue by andreabbondanza** [alexziskind1/nativescript-effects#12]
Hi, it would be amazing if you can create a release for nativescript 7.
You should just change the imports (this is the reason of a new release) in the __tns-effects.d.ts__ file.
```typescript
...
import { View } from '@nativescript/core/ui/core/view';

declare module '@nativescript/core/ui/core/view' { 
...
```

This because the new modules path for NS7 are changed.

Thank you :)

**Comment by alexziskind1** [comment]
That's a great idea. Would you like to try submitting a Pull Request?

**Comment by andreabbondanza** [comment]
Sure, I'll try (it's my first PR)
