### ISSUE TITLE
NativeScript 3.0.0 support?

### ISSUE THREAD

**Issue by toddanglin** [alexziskind1/nativescript-effects#7]
Should this plug-in already be working with NativeScript 3.0.0-rc?

Trying to upgrade a project from 2.4.2 to 3.0.0, and I'm starting to get lots of warnings again about the various effects methods not existing on NativeScript types (despite having typings path in `references.d.ts`). Just curious if this has been tested to work on 3.0.0 so I know if the problem is specific to my app project.

**Comment by alexziskind1** [comment]
NativeScript 3 support is coming. The RC hasn't been tested just yet, but it's certainly on the TODO list

**Comment by toddanglin** [comment]
Cool. Thanks for the update. Happy to hear this is actively getting prepared for 3.0.0.

**Comment by alexziskind1** [comment]
RC3 tested and ready to go. Some changes have been pre-rolled up in the 0.5.0 release so the upgrade should be nothing as long as you get 0.5.0.
